import Head from "next/head";
import { Prompt } from "next/font/google";
import styles from "@/styles/Products.module.css";
import Image from "next/image";
import Link from "next/link";

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
});

function Products() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main2}>
        <div className={styles.productsContainer}>
          <div className={styles.productsContainer__title}>
            <div className={prompt.className}>
              <h1>Nuestros productos</h1>
              <Link href={`/products`}>Ver productos</Link>
            </div>
          </div>
          <div className={styles.productsContainer__products}>
            <div className={styles.productsContainer__product1}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681329988/256_gdz4e1.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product2}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681329988/256_gdz4e1.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product3}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681329988/256_gdz4e1.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product4}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681419094/403_j1quy4.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product5}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681419094/403_j1quy4.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product6}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681419094/403_j1quy4.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product7}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681419094/403_j1quy4.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
            <div className={styles.productsContainer__product8}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681419094/403_j1quy4.png"
                alt="img logo"
                width={300}
                height={250}
              />
              <p>WTS 506</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Products;
