import Head from "next/head";
import styles from "@/styles/Brands.module.css";
import Image from "next/image";
import { Prompt } from "next/font/google";
import brand1 from "../../../public/assets/descargammmmm-removebg-preview.png";
import brand2 from "../../../public/assets/descarga-removebg-preview.png";
import brand3 from "../../../public/assets/descarga__1_-removebg-preview.png";

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
});

function Brands() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.bransContainer}>
        <section className={styles.bransContainer__title}>
          <h1 className={prompt.className}>Marcas asociadas</h1>
        </section>
        <section className={styles.bransContainer__brands}>
          <article className={styles.bransContainer__brand1}>
            <div className={styles.bransContainer__brand__circle}>
              <Image src={brand1} alt="brand1" width={200} height={150} />
            </div>
          </article>
          <article className={styles.bransContainer__brand2}>
            <div className={styles.bransContainer__brand__circle}>
              <Image src={brand2} alt="brand2" width={200} height={150} />
            </div>
          </article>
          <article className={styles.bransContainer__brand3}>
            <div className={styles.bransContainer__brand__circle}>
              <Image src={brand3} alt="brand3" width={200} height={150} />
            </div>
          </article>
        </section>
      </main>
    </>
  );
}

export default Brands;
