import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavBar from "@/components/navBar/navBar";
import Banner from "@/components/banner/banner";
import KnowUs from "@/components/knowUs/knowUs";
import Products from "@/components/products/products";
import Footer from "@/components/footer/footer";
// import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Banner />
      <KnowUs />
      <Products />
      <Footer />
    </>
  );
}

export default Home;
