import Head from "next/head";
import { Prompt } from "next/font/google";
import styles from "@/styles/Footer.module.css";
import { BsFacebook, BsTwitter, BsInstagram } from "react-icons/bs";
import "leaflet/dist/leaflet.css";
import Link from "next/link";

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
});

function Footer() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main2}>
        <div className={styles.footerContainer}>
          <div className={prompt.className}>
            <div className={styles.footerContainer__information}>
              <h1>Contacto</h1>
              <h2>DIRECCION</h2>
              <p>
                Calle 136 # 53-30 <br /> Bogota
              </p>
              <h2>CORREO ELECTRONICO</h2>
              <p>hola@etniaavl.com</p>
              <h2>TELEFONO</h2>
              <p>314 673 0543</p>
              <h2>REDES</h2>
              <p>
                <BsFacebook />
                <BsInstagram />
                <BsTwitter />
              </p>
            </div>
          </div>
          <div className={styles.footerContainer__map}></div>
        </div>
      </main>
    </>
  );
}

export default Footer;
